### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Michailpt** [ClemCa/python-prev#11]
```python
# callback
def callback(num): # error Timeout
    print(num)
def my_fn_2(num, callback):
    num_fn = num + 10
    callback(num_fn) 
num = int(input('input number: '))
my_fn_2(num, callback)

**Comment by ClemCa** [comment]
sorry I totally forgot about your issue, I'm going to check that out later

**Comment by ClemCa** [comment]
Okay this was a complicated one to figure out originally as I didn't look for the right thing. Any input that wasn't preceded by a space or a new line wasn't replaced by a mock value.
I was led astray at the star thinking that there was some unknown issue with currying or something (which wouldn't make sense as it's no special syntax).

**Comment by ClemCa** [comment]
Fixed
