### ISSUE TITLE
TypeErrore

### ISSUE THREAD

**Issue by Michailpt** [ClemCa/python-prev#2]
```Python
a = [1, 2]
b = a
c = b.append(3)
print(a, id(a))
print(b, id(b))  # TypeErrore
print(c)

**Comment by ClemCa** [comment]
Hmm, it looks like the extension doesn't deal with cases when print has multiple arguments. I'll fix it when I have time. It'll probably be done by tomorrow.

**Comment by ClemCa** [comment]
The bug was fixed in the latest update. Thank you for the report.
