### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Michailpt** [ClemCa/python-prev#3]
Greetings
```Python
films = { # SyntaxError
    'A': {'r': 4.9,'r1': 'review'},
    'B': {'r': 4.6,'r1': 'review'},
    'C': {'r': 3.8,'r1': 'review'},
    'D': {'r': 2.3,'r1': 'review'}}
print(films)

**Comment by ClemCa** [comment]
This was (yet) another oversight. The extension doesn't deal well with multiline instructions that do not use \.
I will fix that later by ensuring all open brackets are closed before considering a statement complete.

**Comment by ClemCa** [comment]
I can't test my fix on my current setup, but I will do so by tomorrow. If it works, I will publish and close this.

**Comment by ClemCa** [comment]
It's up! @Michailpt 
Thank you very much for providing such easily reproducible code snippets for your issues. It really makes my life so much easier.
