### ISSUE TITLE
Unstable operation.

### ISSUE THREAD

**Issue by Michailpt** [ClemCa/python-prev#5]
When the plugin is enabled, some keys and key combinations stop working, for example Enter or ctrl+z (undo).
After pasting a copied piece of code, the plugin stops working, deleting the pasted code does not fix the situation, only a reboot helps.

**Comment by ClemCa** [comment]
Might be about response time.
I have a good idea of how to solve this. I'll make it more responsive.
This will be one of those times where I'll keep the issue open for feedback after updating.

**Comment by Michailpt** [comment]
I found out why the keys stop working and the plugin freezes because of triple quotes. These are exactly
```Python
 """Comments"""

**Comment by ClemCa** [comment]
Oh! I will still take the opportunity to improve performance a tad, but will focus on this first.
I think it's a newly introduced bug too, I remember vividly implementing something that checked for strings in a recent update. There's probably a loop that never closes there.

**Comment by ClemCa** [comment]
I just made the update, including something that should help with performance, do keep me updated on how it feels.

**Comment by Michailpt** [comment]
The plugin no longer hangs completely if there is an error, it hangs if you fix it.
``` Python
my_dict = {'a': 1, 'b': 2, 'c': 3}
id_key = my_dict['a'] # The plugin hangs on this line, does not write an error
asd = 123

**Comment by ClemCa** [comment]
It was a simple off-by-1 error in the bounds of the loop that deals with multilines.
I had an < len check when I used ++line and not line++ inside.
The patch is up

**Comment by ClemCa** [comment]
As mentioned earlier, I'll keep that issue open for further feedback on multiline strings and performance.
When you feel like there's nothing more to say, don't hesitate to close it yourself.

**Comment by Michailpt** [comment]
```python
my_dict = {'id': 123, 'rev': [1, 2]}
new_dict = my_dict.copy() 
if isinstance(new_dict['rev'], list):  # Error
    new_dict['rev'].append(3)
a = 1

**Comment by ClemCa** [comment]
Seems like that was an issue born out of a brain fart. I checked if a string had been found instead of whether we were still in one so the second bracket after 'rev' was ignored.

**Comment by Michailpt** [comment]
Good morning.
```python 
str1 = 'New string'
print(str1.find('s', 5)) # Error
print(str1.replace('s','S')) # Error

**Comment by ClemCa** [comment]
That's a bug in a completely different area, it seems like we're done with this issue.
I'll create a new issue from that.
